### PR TITLE
Use watchQuery for atomsWithQuery

### LINKED ISSUE #9: Does `atomsWithQuery` subscribe to apollo store?
I see that atomsWithQuery uses `client.query` instead of `watchQuery`. This implies that the atom won't be updated when there's a change in apollo store that would impact the query result (e.g. another query updating the cache with some cache keys in common with this query). Wondering what the rationale is and whether it was intentional.

https://github.com/jotaijs/jotai-apollo/blob/master/src/atomsWithQuery.ts#L37-L40

### PR DESCRIPTION
**Pull request by dsonck92**
Closes: #9

### CODE REVIEW

**Comment by dsonck92** [comment]
Since it's already using an `Observer`, and the `watchQuery` returns an `Observer` as well, all the logic can be reduced to just calling `client.watchQuery`. At least this fixes the refresh on my own project.

I would consider any further features, other than just plainly handling the observer, out of scope and to be dealt with when the need arises.

**Comment by dsonck92** [comment]
Ah yes, it seems like there was a query mock in place that doesn't work anymore. I will try to rewrite the tests to use `MockLink` from apollo instead so we can build on a more vanilla `ApolloClient` later today.

**Review by Aslemammad — APPROVED** [review]
@dsonck92 Thank you so much, I appreciate the PR, let's fix the tests and merge!

**Comment by dsonck92** [comment]
Seems like the tests so far also get simplified by leveraging the MockLink. Currently tackling the refetch test but then it should work.

**Comment by dsonck92** [comment]
Locally I got all tests running. Main changes are:
- Drop the custom mock for apollo's own `MockLink` which goes through the cache
- Change the `Math.random()` to a more predictable input so the `MockLink` actually has known inputs

Though I will say, I don't exactly know what that last function is really supposed to test. Though it does show it can retrigger the query getting function.

**Review by Aslemammad — APPROVED** [review]
LGTM. @dai-shi Could you check this, so I can merge and release?

**Review by dai-shi — APPROVED** [review]
The code looks much cleaner. Thanks!

**Pull request merged**
